site_name: Freqtrade 中文版
site_url: !ENV [READTHEDOCS_CANONICAL_URL, 'https://www.freqtrade.io/en/']
site_description: Freqtrade is a free and open source crypto trading bot written in Python, designed to support all major exchanges and be controlled via Telegram or builtin Web UI
repo_url: https://github.com/freqtrade/freqtrade
edit_uri: edit/develop/docs/
use_directory_urls: True
nav:
    - 首页: index.md
    - Docker快速入门: docker_quickstart.md
    - 安装指南:
        - Linux/MacOS/树莓派: installation.md
        - Windows系统: windows_installation.md
    - Freqtrade基础: bot-basics.md
    - 配置说明: configuration.md
    - 策略快速入门: strategy-101.md
    - 策略自定义: strategy-customization.md
    - 策略回调函数: strategy-callbacks.md
    - 止损设置: stoploss.md
    - 插件系统: plugins.md
    - 启动机器人: bot-usage.md
    - 控制机器人:
        - Telegram控制: telegram-usage.md
        - freqUI界面: freq-ui.md
        - REST API接口: rest-api.md
        - Web钩子配置: webhook-config.md
    - 数据下载: data-download.md
    - 回测系统: backtesting.md
    - 超参数优化: hyperopt.md
    - FreqAI智能系统:
        - 介绍: freqai.md
        - 配置说明: freqai-configuration.md
        - 参数表: freqai-parameter-table.md
        - 特征工程: freqai-feature-engineering.md
        - 运行FreqAI: freqai-running.md
        - 强化学习: freqai-reinforcement-learning.md
        - 开发者指南: freqai-developers.md
    - 做空/杠杆交易: leverage.md
    - 实用子命令: utils.md
    - 数据可视化: plotting.md
    - 交易所特别说明: exchanges.md
    - 数据分析:
        - Jupyter笔记本: data-analysis.md
        - 策略分析: strategy_analysis_example.md
        - 回测分析: advanced-backtesting.md
    - 高级主题:
        - 高级安装后任务: advanced-setup.md
        - 交易对象: trade-object.md
        - 前瞻性分析: lookahead-analysis.md
        - 递归分析: recursive-analysis.md
        - 高级策略: strategy-advanced.md
        - 高级超参数优化: advanced-hyperopt.md
        - 订单流: advanced-orderflow.md
        - 生产者/消费者模式: producer-consumer.md
        - SQL速查表: sql_cheatsheet.md
        - 边缘定位: edge.md
    - 常见问题: faq.md
    - 策略迁移: strategy_migration.md
    - 更新Freqtrade: updating.md
    - 已弃用功能: deprecated.md
    - 贡献者指南: developer.md
theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/logo.png"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
extra:
  version:
    provider: mike
    alias: true
  analytics:
    provider: google
    property: G-VH170LG9M5
plugins:
  - search:
      enabled: true
  - mike:
      deploy_prefix: 'en'
      canonical_version: 'stable'
